### ISSUE TITLE
PR

### ISSUE THREAD

**Issue by DolphaGo** [yuri-von-gella/awesome-michelin#4]
[Member]
Assignees는 본인으로 설정해주시고, reviewer는 그냥 전체다 걸으셔도 됩니다 ㅎㅎㅎ
아무나 두 분만 확인해주시고 머지해주세요. 

[Visitor]
추가하고 싶은 리스트를 기존 데이터 아래에 추가해주시면 됩니다.
* 가게 이름 및 링크
    - 설명1(자유양식)
    - 설명2(자유양식)

**Comment by Dinoryong** [comment]
네네넹
